### ISSUE TITLE
Re-restore fail upon database online  check

### ISSUE THREAD

**Issue by SamuraiTheNinja** [MonitoringSolutionsInc/DatabaseBackupTool#32]
This issue should not be encountered in normal use. However if an active database is not in the "online" state & is not being restored with this tool, in theory the code would break. This is because the code checks all active databases state upon completion and tries to restore any that aren't online.

In reference to this code block:

https://github.com/MonitoringSolutionsInc/DatabaseBackupTool/blob/542a4cca7266b3db0c10402cbb7a3746c6ff6db1/DatabaseBackupTool/Restore.cs#L223-L292

**Comment by JazzGlobal** [comment]
If this happens and the code finds the database in any other states besides "online" ... What happens? Will it crash when attempting to restore or will it get stuck in a loop?

**Comment by JazzGlobal** [comment]
Obviously the restore would fail because it would not find the file. If it gets caught in a loop then we'll probably want to resolve this problem with an additional check to make sure the file exists. You could probably break out of the loop / stop the recursion. 

This seems to be the line that forces it to loop:
https://github.com/MonitoringSolutionsInc/DatabaseBackupTool/blob/542a4cca7266b3db0c10402cbb7a3746c6ff6db1/DatabaseBackupTool/Restore.cs#L289

I don't think we want to change that particular piece of code. Instead of using the following to check for !ONLINE databases:
https://github.com/MonitoringSolutionsInc/DatabaseBackupTool/blob/542a4cca7266b3db0c10402cbb7a3746c6ff6db1/DatabaseBackupTool/Restore.cs#L228

Perhaps we could further filter it by matching it against the temp database list? This could get messy when recursively restoring since it'd have to check all sub folders, at worst case, to find the file.
